# These are the repositories where the application looks for DX issues.
# We mainly track Symfony repos, the most important bundles and some
# important projects that belong to the Symfony ecosystem.
#
# Note: All the repositories must be hosted at GitHub. The following list
#       only includes the vendor and repo name parts (prepend each line with
#       'https://github.com/' to get the absolute URL of each repository)

repositories:
    high_priority:
        - symfony/symfony
        - symfony/symfony-docs
        - symfony/symfony-standard
        - doctrine/DoctrineBundle

    low_priority:
        - avalanche123/AvalancheImagineBundle
        - doctrine/DoctrineCouchDBBundle
        - doctrine/DoctrineFixturesBundle
        - doctrine/DoctrineMigrationsBundle
        - doctrine/DoctrineMongoDBBundle
        - doctrine/DoctrinePHPCRBundle
        - dustin10/VichUploaderBundle
        - fabpot/Goutte
        - fabpot/PHP-CS-Fixer
        - fabpot/Pimple
        - fabpot/Sami
        - fabpot/twig
        - fabpot/Twig-extensions
        - FriendsOfSymfony/FOSElasticaBundle
        - FriendsOfSymfony/FOSJsRoutingBundle
        - FriendsOfSymfony/FOSRestBundle
        - FriendsOfSymfony/FOSUserBundle
        - genemu/GenemuFormBundle
        - hwi/HWIOAuthBundle
        - KnpLabs/KnpGaufretteBundle
        - KnpLabs/KnpMenuBundle
        - KnpLabs/KnpPaginatorBundle
        - KnpLabs/KnpSnappyBundle
        - lexik/LexikFormFilterBundle
        - liip/LiipImagineBundle
        - liuggio/ExcelBundle
        - nelmio/NelmioApiDocBundle
        - phiamo/MopaBootstrapBundle
        - raulfraile/LadybugBundle
        - schmittjoh/JMSDiExtraBundle
        - schmittjoh/JMSI18nRoutingBundle
        - schmittjoh/JMSSecurityExtraBundle
        - schmittjoh/JMSSerializerBundle
        - schmittjoh/JMSTranslationBundle
        - sensiolabs/SensioDistributionBundle
        - sensiolabs/SensioFrameworkExtraBundle
        - sensiolabs/SensioGeneratorBundle
        - silexphp/Silex
        - silexphp/Silex-Skeleton
        - silexphp/Silex-WebProfiler
        - snc/SncRedisBundle
        - sonata-project/SonataAdminBundle
        - stof/StofDoctrineExtensionsBundle
        - swiftmailer/swiftmailer
        - symfony-cmf/BlockBundle
        - symfony-cmf/BlogBundle
        - symfony-cmf/ContentBundle
        - symfony-cmf/CoreBundle
        - symfony-cmf/CreateBundle
        - symfony-cmf/MediaBundle
        - symfony-cmf/MenuBundle
        - symfony-cmf/RoutingAutoBundle
        - symfony-cmf/RoutingBundle
        - symfony-cmf/SearchBundle
        - symfony-cmf/SeoBundle
        - symfony-cmf/SimpleCmsBundle
        - symfony-cmf/symfony-cmf
        - symfony-cmf/symfony-cmf-docs
        - symfony-cmf/Testing
        - symfony-cmf/TreeBrowserBundle
        - symfony/AsseticBundle
        - symfony/MonologBundle
        - symfony/SwiftmailerBundle
        - whiteoctober/WhiteOctoberPagerfantaBundle
